# -*- coding: utf-8 -*-
"""yolofinaly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtxUtREavn35rBAA2AlWSV09ywA61Xlr
"""

from google.colab import drive
drive.mount('/content/drive')

dataset_path = "/content/drive/MyDrive/yolodataset"  # Update this if needed

train_img_path = f"{dataset_path}/images/train"
val_img_path = f"{dataset_path}/images/val"
train_lbl_path = f"{dataset_path}/labels/train"
val_lbl_path = f"{dataset_path}/labels/val"

import os
# Extract unique goat names from label file names
goat_names = sorted([os.path.splitext(f)[0] for f in os.listdir(train_lbl_path) if f.endswith(".txt")])

# Number of unique goats
num_classes = len(goat_names)

# Build data.yaml content
yaml_content = f"""train: {train_img_path}
val: {val_img_path}

nc: {num_classes}
names: {goat_names}
"""

# Write to data.yaml
yaml_file = f"{dataset_path}/data.yaml"
with open(yaml_file, "w") as f:
    f.write(yaml_content)

print(f"✅ data.yaml created successfully at {yaml_file}")
print(f"Classes ({num_classes}): {goat_names}")

!pip install ultralytics

from ultralytics import YOLO

# Load YOLO model
model = YOLO("yolov8n.pt")  # Use "yolov8s.pt" or "yolov8m.pt" for better accuracy

# Train the model
model.train(
    data=f"{dataset_path}/data.yaml",
    epochs=50,  # Adjust for better performance
    imgsz=640,
    batch=8,  # Adjust based on GPU memory
    device="cuda"  # Use GPU if available
)

# Validate the trained model
metrics = model.val()
print(metrics)

print("Results saved in:", results[0].save_dir)

import os
from PIL import Image
import IPython.display as display

# Run inference on a sample validation image
results = model.predict(source=f"{val_img_path}/class108_03.png", save=True)
output_folder = results[0].save_dir  # Get YOLO's output folder

output_image_path = os.path.join(output_folder, "class108_03.jpg")  # ✅ Correct
output_image = Image.open(output_image_path)
display.display(output_image)